apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-todo-backend
  template:
    metadata:
      labels:
        app: mern-todo-backend
    spec:
      containers:
      - name: mern-todo-backend
        image: altsang/mern-todo-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: mongodb://mern-todo-mongo:27017/mern-todo
---
apiVersion: v1
kind: Service
metadata:
  name: mern-todo-backend
spec:
  selector:
    app: mern-todo-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
