apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-todo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-todo-frontend
  template:
    metadata:
      labels:
        app: mern-todo-frontend
    spec:
      containers:
      - name: mern-todo-frontend
        image: altsang/mern-todo-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://mern-todo-backend:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-todo-frontend
spec:
  selector:
    app: mern-todo-frontend
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
