apiVersion: v1
kind: Service
metadata:
  name: mern-todo-backend-service
spec:
  selector:
    app: mern-todo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
