apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-job
spec:
  template:
    spec:
      containers:
      - name: mongodb-init
        image: mongo:latest
        command: ["/bin/bash", "-c", "mongo --host mongodb-service --eval 'db.createCollection(\"todos\");'"]
      restartPolicy: Never
  backoffLimit: 4
