apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-job
spec:
  template:
    spec:
      containers:
      - name: mongodb-init
        image: mongo:4.2
        command: ["sh", "-c", "until mongo --host mongodb-service --eval 'db.createCollection(\"todos\");'; do echo waiting for mongo; sleep 2; done"]
      restartPolicy: Never
  backoffLimit: 4
